module core.game {
	export interface IConfigKey {
		/**
         * 技能模板
         */
		JiNengMoBan: string;
		JueSe: string;
		JueSeWaiXian: string;
		GongNeng: string;
		zhuangbeibiao: string;
		/**
		 * 
		 * 所有道具配置
		 * @type {string}
		 */
		AllItems: string;
		CeShiBiao: string;
		ZhuangBeiPinZhi: string;
		guanqia: string;
		daoju: string;
		/**
         * 技能
         */
		JiNengBiao: string;
		CdBiao: string;
		beibaomax: string;
		ZhiYeBiaoNew: string;
		GuaiWuBiao: string;
		ZhuXianRenWu: string;
		CaiLiaoFuBen: string;
		CaiLiaoFuBenGouMai: string;
		Guild: string;
		GuildCreate: string;
		GuildPosition: string;
		GuildDonation: string;
		ChengJiu: string;
		ChengHaoBiao: string;
		ZhuangBeiShuXingBiao: string;
		ZhanDouLiXiShu: string;
		ChiBangBiao: string;
		GuildMine: string;
		Config: string;
		BossZhaoHuan: string;
		GuildZhanQi: string;
		JingYanShenDeng: string;
		JingYanShenDengKaiGuang: string;
		JingYanShenDengPinJieBiao: string;
		JingYanShenDengShuXingBiao: string;
		Vip: string;
		FaBaoBiao: string;
		FaBaoShengJiBiao: string;
		FaBaoShengXing: string;
		FaBaoHeCheng: string;
		JiNengChengZhang: string;
		MapLine: string;
		ZhuangBeiqianghuaShuXingBiao: string;
		ZhengZhan: string;
		ZhengZhanJiangLi: string;
		HuoYueJiangLi: string;
		ShenLu: string;
		YinLingBiao: string;
		YinLingShengJie: string;
		JingJiChang: string;
		JieMianHuChi: string;
		JingJiChangGuiZe: string;
		ShenQiBiao: string;
		ShenQiZhuanSheng: string;
		TongTianTa: string;
		TongTianTaBaoKu: string;
		PhaseAction: string;
		PhaseUnit: string;
		Sex: string;
		MoBai: string;
		XuNiHuoBi: string;
		ShouChong: string;
		GuildFuBen: string;
		GuildFuBenBoss: string;
		FaBaoJiNeng: string;
		GuildKuangChang: string;
		GuildKuangChangJiLi: string;
		ChengZhangBiao: string;
		GuildTask: string;
		ChengHaoChengZhang: string;
		GuaJiChanChu: string;
		BaoXiang: string;
		GuildBaoKu: string;
		BuWeiDuiYingShuXing: string;
		GongNengKaiFang: string;
		YueKa: string;
		YinDao: string;
		TuJing: string;
		XunBao: string;
		ZhaoHuanWu: string;
		Exchange: string;
		QiRiDengLu: string;
		shibaijiesuan: string;
		baoshibiao: string;
		baoshikong: string;
		MeiRiHuoDong: string;
		YingHunZengJia: string;
		YingHunShengJi: string;
		ShengCunPaiMing: string;
		ShengCunTiaoZhan: string;
		ChengGongLv: string;
		YingHunPinJie: string;
		LianTi: string;
		ShengCunjisha: string;
		pingzhixishu: string;
		DengJiLiBao: string;
		FenJieBiao: string;
		VipFuBen: string;
		WeiDuanJiangLi: string;
		FenXiangJiangLi: string;
		GuanZhuJiangLi: string;
		ZhuangBeiFuBen: string;
		YingLingFuBen: string;
		ShenLuFuBen: string;
		HongZhuangHeCheng: string;
		HeCheng: string;
		ZhuangBeiXiLianShuXing: string;
		ShuZhiSuiJi: string;
		ShuXingSuiJi: string;
		XiLianXiaoHao: string;
		JiChengXiaoHao: string;
		TaoZhuangBiao: string;
		XingJiSuiJi: string;
		ChengZhangJiJin: string;
		ChengZhangJiJinJiangLi: string;
		ZhangJieHuoYueJiangLi: string;
		HongTuBaYe: string;
		JinDuQuYu: string;
		HongTuBaYeJiangLi: string;
		ZhaoHui: string;
		GongNengKaiFangTiShi: string;
		SevenRiRenWu: string;
		GeRenJiangLi: string;
		ShenQiJiHuo: string;
		ShenQiJinJieShuXing: string;
		GongMingJianSuo: string;
		FaBaoGongMing: string;
		ZhengZhanLueDuo: string;
		PeiDaiGeZiKaiQi: string;
		ChengHaoShouJi: string;
		XiaoGuoBiao: string;
		MoHunShangDian: string;
		ZhuangBeiFenJie: string;
		GuildKuangChangKaiQi: string;
		DingZhiHuaZhuangBei: string;
		DiaoLuoBao: string;
		QianDao: string;
		TuZhiHeCheng: string;
		CangBaoGe: string;
		GongMingTuPu: string;
		ChiBangHuanHua: string;
		ChuanQiZhiZun: string;
		ShaBaKeTiaoZhan: string;
		ShaBaKePaiMing: string;
		GuanXingTai: string;
		GuanXingTaiXingZuo: string;
		XianShiBoss: string;
		ChengZhu: string;
	}
	ConfigKey = {
		MAP: "maps",
		PST: "pst",
		ANI: "ani",
		JiNengMoBan: "JiNengMoBan",
		JueSe: "JueSe",
		JueSeWaiXian: "JueSeWaiXian",
		GongNeng: "GongNeng",
		zhuangbeibiao: "zhuangbeibiao",
		AllItems: "AllItems",
		CeShiBiao: "CeShiBiao",
		ZhuangBeiPinZhi: "ZhuangBeiPinZhi",
		guanqia: "guanqia",
		daoju: "daoju",
		JiNengBiao: "JiNengBiao",
		CdBiao: "CdBiao",
		beibaomax: "beibaomax",
		ZhiYeBiaoNew: "ZhiYeBiaoNew",
		GuaiWuBiao: "GuaiWuBiao",
		ZhuXianRenWu: "ZhuXianRenWu",
		CaiLiaoFuBen: "CaiLiaoFuBen",
		CaiLiaoFuBenGouMai: "CaiLiaoFuBenGouMai",
		Guild: "Guild",
		GuildCreate: "GuildCreate",
		GuildPosition: "GuildPosition",
		GuildDonation: "GuildDonation",
		ChengJiu: "ChengJiu",
		ChengHaoBiao: "ChengHaoBiao",
		ZhuangBeiShuXingBiao: "ZhuangBeiShuXingBiao",
		ZhanDouLiXiShu: "ZhanDouLiXiShu",
		ChiBangBiao: "ChiBangBiao",
		GuildMine: "GuildMine",
		Config: "Config",
		BossZhaoHuan: "BossZhaoHuan",
		GuildZhanQi: "GuildZhanQi",
		JingYanShenDeng: "JingYanShenDeng",
		JingYanShenDengKaiGuang: "JingYanShenDengKaiGuang",
		JingYanShenDengPinJieBiao: "JingYanShenDengPinJieBiao",
		JingYanShenDengShuXingBiao: "JingYanShenDengShuXingBiao",
		Vip: "Vip",
		FaBaoBiao: "FaBaoBiao",
		FaBaoShengJiBiao: "FaBaoShengJiBiao",
		FaBaoShengXing: "FaBaoShengXing",
		FaBaoHeCheng: "FaBaoHeCheng",
		JiNengChengZhang: "JiNengChengZhang",
		MapLine: "MapLine",
		ZhuangBeiqianghuaShuXingBiao: "ZhuangBeiqianghuaShuXingBiao",
		ZhengZhan: "ZhengZhan",
		ZhengZhanJiangLi: "ZhengZhanJiangLi",
		HuoYueJiangLi: "HuoYueJiangLi",
		ShenLu: "ShenLu",
		YinLingBiao: "YinLingBiao",
		YinLingShengJie: "YinLingShengJie",
		JingJiChang: "JingJiChang",
		JieMianHuChi: "JieMianHuChi",
		JingJiChangGuiZe: "JingJiChangGuiZe",
		ShenQiBiao: "ShenQiBiao",
		ShenQiZhuanSheng: "ShenQiZhuanSheng",
		TongTianTa: "TongTianTa",
		TongTianTaBaoKu: "TongTianTaBaoKu",
		PhaseAction: "PhaseAction",
		PhaseUnit: "PhaseUnit",
		Sex: "Sex",
		MoBai: "MoBai",
		XuNiHuoBi: "XuNiHuoBi",
		ShouChong: "ShouChong",
		GuildFuBen: "GuildFuBen",
		GuildFuBenBoss: "GuildFuBenBoss",
		FaBaoJiNeng: "FaBaoJiNeng",
		GuildKuangChang: "GuildKuangChang",
		GuildKuangChangJiLi: "GuildKuangChangJiLi",
		ChengZhangBiao: "ChengZhangBiao",
		GuildTask: "GuildTask",
		ChengHaoChengZhang: "ChengHaoChengZhang",
		GuaJiChanChu: "GuaJiChanChu",
		BaoXiang: "BaoXiang",
		GuildBaoKu: "GuildBaoKu",
		BuWeiDuiYingShuXing: "BuWeiDuiYingShuXing",
		GongNengKaiFang: "GongNengKaiFang",
		YueKa: "YueKa",
		YinDao: "YinDao",
		TuJing: "TuJing",
		XunBao: "XunBao",
		ZhaoHuanWu: "ZhaoHuanWu",
		Exchange: "Exchange",
		QiRiDengLu: "QiRiDengLu",
		shibaijiesuan: "shibaijiesuan",
		baoshibiao: "baoshibiao",
		baoshikong: "baoshikong",
		MeiRiHuoDong: "MeiRiHuoDong",
		YingHunZengJia: "YingHunZengJia",
		YingHunShengJi: "YingHunShengJi",
		ShengCunPaiMing: "ShengCunPaiMing",
		ShengCunTiaoZhan: "ShengCunTiaoZhan",
		ChengGongLv: "ChengGongLv",
		YingHunPinJie: "YingHunPinJie",
		LianTi: "LianTi",
		ShengCunjisha: "ShengCunjisha",
		pingzhixishu: "pingzhixishu",
		DengJiLiBao: "DengJiLiBao",
		FenJieBiao: "FenJieBiao",
		VipFuBen: "VipFuBen",
		WeiDuanJiangLi: "WeiDuanJiangLi",
		FenXiangJiangLi: "FenXiangJiangLi",
		GuanZhuJiangLi: "GuanZhuJiangLi",
		ZhuangBeiFuBen: "ZhuangBeiFuBen",
		YingLingFuBen: "YingLingFuBen",
		ShenLuFuBen: "ShenLuFuBen",
		HongZhuangHeCheng: "HongZhuangHeCheng",
		HeCheng: "HeCheng",
		ZhuangBeiXiLianShuXing: "ZhuangBeiXiLianShuXing",
		ShuZhiSuiJi: "ShuZhiSuiJi",
		ShuXingSuiJi: "ShuXingSuiJi",
		XiLianXiaoHao: "XiLianXiaoHao",
		JiChengXiaoHao: "JiChengXiaoHao",
		TaoZhuangBiao: "TaoZhuangBiao",
		XingJiSuiJi: "XingJiSuiJi",
		ChengZhangJiJin: "ChengZhangJiJin",
		ChengZhangJiJinJiangLi: "ChengZhangJiJinJiangLi",
		ZhangJieHuoYueJiangLi: "ZhangJieHuoYueJiangLi",
		HongTuBaYe: "HongTuBaYe",
		JinDuQuYu: "JinDuQuYu",
		HongTuBaYeJiangLi: "HongTuBaYeJiangLi",
		ZhaoHui: "ZhaoHui",
		GongNengKaiFangTiShi: "GongNengKaiFangTiShi",
		SevenRiRenWu: "SevenRiRenWu",
		GeRenJiangLi: "GeRenJiangLi",
		ShenQiJiHuo: "ShenQiJiHuo",
		ShenQiJinJieShuXing: "ShenQiJinJieShuXing",
		GongMingJianSuo: "GongMingJianSuo",
		FaBaoGongMing: "FaBaoGongMing",
		ZhengZhanLueDuo: "ZhengZhanLueDuo",
		PeiDaiGeZiKaiQi: "PeiDaiGeZiKaiQi",
		ChengHaoShouJi: "ChengHaoShouJi",
		XiaoGuoBiao: "XiaoGuoBiao",
		MoHunShangDian: "MoHunShangDian",
		ZhuangBeiFenJie: "ZhuangBeiFenJie",
		GuildKuangChangKaiQi: "GuildKuangChangKaiQi",
		DingZhiHuaZhuangBei: "DingZhiHuaZhuangBei",
		DiaoLuoBao: "DiaoLuoBao",
		QianDao: "QianDao",
		TuZhiHeCheng: "TuZhiHeCheng",
		CangBaoGe: "CangBaoGe",
		GongMingTuPu: "GongMingTuPu",
		ChiBangHuanHua: "ChiBangHuanHua",
		ChuanQiZhiZun: "ChuanQiZhiZun",
		ShaBaKeTiaoZhan: "ShaBaKeTiaoZhan",
		ShaBaKePaiMing: "ShaBaKePaiMing",
		GuanXingTai: "GuanXingTai",
		GuanXingTaiXingZuo: "GuanXingTaiXingZuo",
		XianShiBoss: "XianShiBoss",
		ChengZhu: "ChengZhu",
	}
	function rP(key: string, CfgCreator: { new (): ICfg }, idkey: string = "id") {
		DataLocator.regCommonParser(key, CfgCreator, idkey);
	}
	function rE(key: string) {
		DataLocator.regExtra(key);
	}
	export function initData() {
		var C = ConfigKey;
		var P = core.game;
		rP(C.GongNeng, P.GongNengCfg);
		/*rP(C.JiNengMoBan, P.JiNengMoBanCfg);
		rP(C.JueSe, P.JueSeCfg, "level");
		rP(C.JueSeWaiXian, P.JueSeWaiXianCfg);
		rP(C.daoju, P.daojuCfg);
		rP(C.zhuangbeibiao, P.zhuangbeibiaoCfg);
		rP(C.ZhuangBeiPinZhi, P.ZhuangBeiPinZhiCfg, "rare");
		rP(C.guanqia, P.guanqiaCfg);
		rP(C.JiNengBiao, P.JiNengBiaoCfg);
		rP(C.CdBiao, P.CdBiaoCfg);
		rP(C.beibaomax, P.beibaomaxCfg);
		rP(C.GuaiWuBiao, P.GuaiWuBiaoCfg);
		rP(C.ZhuXianRenWu, P.ZhuXianRenWuCfg);
		rP(C.CaiLiaoFuBen, P.CaiLiaoFuBenCfg);
		rP(C.CaiLiaoFuBenGouMai, P.CaiLiaoFuBenGouMaiCfg);
		rP(C.Guild, P.GuildCfg);
		rP(C.GuildCreate, P.GuildCreateCfg);
		rP(C.GuildPosition, P.GuildPositionCfg);
		rP(C.GuildDonation, P.GuildDonationCfg);
		rP(C.ChengHaoBiao, P.ChengHaoBiaoCfg);
		rP(C.ZhuangBeiShuXingBiao, P.ZhuangBeiShuXingBiaoCfg);
		rP(C.ZhanDouLiXiShu, P.ZhanDouLiXiShuCfg);
		rP(C.ChiBangBiao, P.ChiBangBiaoCfg);
		rP(C.GuildMine, P.GuildMineCfg);
		rP(C.ZhiYeBiaoNew, P.ZhiYeBiaoNewCfg);
		rP(C.Config, P.ConfigCfg);
		rP(C.BossZhaoHuan, P.BossZhaoHuanCfg);
		rP(C.GuildZhanQi, P.GuildZhanQiCfg);
		rP(C.JingYanShenDeng, P.JingYanShenDengCfg);
		rP(C.JingYanShenDengKaiGuang, P.JingYanShenDengKaiGuangCfg);
		rP(C.JingYanShenDengPinJieBiao, P.JingYanShenDengPinJieBiaoCfg);
		rP(C.JingYanShenDengShuXingBiao, P.JingYanShenDengShuXingBiaoCfg);
		rP(C.Vip, P.VipCfg);
		rP(C.FaBaoBiao, P.FaBaoBiaoCfg);
		rP(C.FaBaoShengJiBiao, P.FaBaoShengJiBiaoCfg);
		rP(C.FaBaoShengXing, P.FaBaoShengXingCfg);
		rP(C.FaBaoHeCheng, P.FaBaoHeChengCfg);
		rP(C.JiNengChengZhang, P.JiNengChengZhangCfg);
		rP(C.MapLine, P.MapLineCfg);
		rP(C.ZhuangBeiqianghuaShuXingBiao, P.ZhuangBeiqianghuaShuXingBiaoCfg);
		rP(C.ZhengZhan, P.ZhengZhanCfg);
		rP(C.ZhengZhanJiangLi, P.ZhengZhanJiangLiCfg);
		rP(C.HuoYueJiangLi, P.HuoYueJiangLiCfg);
		rP(C.ShenLu, P.ShenLuCfg);
		rP(C.YinLingBiao, P.YinLingBiaoCfg);
		rP(C.YinLingShengJie, P.YinLingShengJieCfg);
		rP(C.JingJiChang, P.JingJiChangCfg);
		rP(C.JieMianHuChi, P.JieMianHuChiCfg);
		rP(C.JingJiChangGuiZe, P.JingJiChangGuiZeCfg);
		rP(C.ShenQiBiao, P.ShenQiBiaoCfg);
		rP(C.ShenQiZhuanSheng, P.ShenQiZhuanShengCfg);
		rP(C.TongTianTa, P.TongTianTaCfg);
		rP(C.TongTianTaBaoKu, P.TongTianTaBaoKuCfg);
		rP(C.PhaseAction, P.PhaseActionCfg);
		rP(C.PhaseUnit, P.PhaseUnitCfg);
		rP(C.Sex, P.SexCfg);
		rP(C.MoBai, P.MoBaiCfg);
		rP(C.XuNiHuoBi, P.XuNiHuoBiCfg);
		rP(C.ShouChong, P.ShouChongCfg);
		rP(C.GuildFuBen, P.GuildFuBenCfg);
		rP(C.GuildFuBenBoss, P.GuildFuBenBossCfg);
		rP(C.FaBaoJiNeng, P.FaBaoJiNengCfg);
		rP(C.GuildKuangChang, P.GuildKuangChangCfg);
		rP(C.GuildKuangChangJiLi, P.GuildKuangChangJiLiCfg);
		rP(C.ChengZhangBiao, P.ChengZhangBiaoCfg);
		rP(C.GuildTask, P.GuildTaskCfg);
		rP(C.ChengHaoChengZhang, P.ChengHaoChengZhangCfg);
		rP(C.GuaJiChanChu, P.GuaJiChanChuCfg);
		rP(C.BaoXiang, P.BaoXiangCfg);
		rP(C.GuildBaoKu, P.GuildBaoKuCfg);
		rP(C.BuWeiDuiYingShuXing, P.BuWeiDuiYingShuXingCfg);
		rP(C.GongNengKaiFang, P.GongNengKaiFangCfg);
		rP(C.YueKa, P.YueKaCfg);
		rP(C.YinDao, P.YinDaoCfg);
		rP(C.TuJing, P.TuJingCfg);
		rP(C.XunBao, P.XunBaoCfg);
		rP(C.ZhaoHuanWu, P.ZhaoHuanWuCfg);
		rP(C.Exchange, P.ExchangeCfg);
		rP(C.shibaijiesuan, P.shibaijiesuanCfg);
		rP(C.baoshibiao, P.baoshibiaoCfg);
		rP(C.baoshikong, P.baoshikongCfg);
		rP(C.MeiRiHuoDong, P.MeiRiHuoDongCfg);
		rP(C.YingHunZengJia, P.YingHunZengJiaCfg);
		rP(C.YingHunShengJi, P.YingHunShengJiCfg);
		rP(C.ShengCunPaiMing, P.ShengCunPaiMingCfg);
		rP(C.ShengCunTiaoZhan, P.ShengCunTiaoZhanCfg);
		rP(C.ChengGongLv, P.ChengGongLvCfg);
		rP(C.YingHunPinJie, P.YingHunPinJieCfg);
		rP(C.LianTi, P.LianTiCfg);
		rP(C.ShengCunjisha, P.ShengCunjishaCfg);
		rP(C.pingzhixishu, P.pingzhixishuCfg);
		rP(C.DengJiLiBao, P.DengJiLiBaoCfg);
		rP(C.FenJieBiao, P.FenJieBiaoCfg);
		rP(C.WeiDuanJiangLi, P.WeiDuanJiangLiCfg);
		rP(C.FenXiangJiangLi, P.FenXiangJiangLiCfg);
		rP(C.GuanZhuJiangLi, P.GuanZhuJiangLiCfg);
		rP(C.ZhuangBeiFuBen, P.ZhuangBeiFuBenCfg);
		rP(C.YingLingFuBen, P.YingLingFuBenCfg);
		rP(C.ShenLuFuBen, P.ShenLuFuBenCfg);
		rP(C.VipFuBen, P.VipFuBenCfg);
		rP(C.HongZhuangHeCheng, P.HongZhuangHeChengCfg);
		rP(C.HeCheng, P.HeChengCfg);
		rP(C.ZhuangBeiXiLianShuXing, P.ZhuangBeiXiLianShuXingCfg);
		rP(C.ShuZhiSuiJi, P.ShuZhiSuiJiCfg);
		rP(C.ShuXingSuiJi, P.ShuXingSuiJiCfg);
		rP(C.XiLianXiaoHao, P.XiLianXiaoHaoCfg);
		rP(C.JiChengXiaoHao, P.JiChengXiaoHaoCfg);
		rP(C.TaoZhuangBiao, P.TaoZhuangBiaoCfg);
		rP(C.XingJiSuiJi, P.XingJiSuiJiCfg);
		rP(C.ChengZhangJiJin, P.ChengZhangJiJinCfg);
		rP(C.ChengZhangJiJinJiangLi, P.ChengZhangJiJinJiangLiCfg);
		rP(C.ZhangJieHuoYueJiangLi, P.ZhangJieHuoYueJiangLiCfg);
		rP(C.HongTuBaYe, P.HongTuBaYeCfg);
		rP(C.JinDuQuYu, P.JinDuQuYuCfg);
		rP(C.HongTuBaYeJiangLi, P.HongTuBaYeJiangLiCfg);
		rP(C.ZhaoHui, P.ZhaoHuiCfg);
		rP(C.GongNengKaiFangTiShi, P.GongNengKaiFangTiShiCfg);
		rP(C.SevenRiRenWu, P.SevenRiRenWuCfg);
		rP(C.GeRenJiangLi, P.GeRenJiangLiCfg);
		rP(C.ShenQiJiHuo, P.ShenQiJiHuoCfg);
		rP(C.ShenQiJinJieShuXing, P.ShenQiJinJieShuXingCfg);
		rP(C.GongMingJianSuo, P.GongMingJianSuoCfg);
		rP(C.FaBaoGongMing, P.FaBaoGongMingCfg);
		rP(C.ZhengZhanLueDuo, P.ZhengZhanLueDuoCfg);
		rP(C.PeiDaiGeZiKaiQi, P.PeiDaiGeZiKaiQiCfg);
		rP(C.ChengHaoShouJi, P.ChengHaoShouJiCfg);
		rP(C.XiaoGuoBiao, P.XiaoGuoBiaoCfg);
		rP(C.MoHunShangDian, P.MoHunShangDianCfg);
		rP(C.ZhuangBeiFenJie, P.ZhuangBeiFenJieCfg);
		rP(C.GuildKuangChangKaiQi, P.GuildKuangChangKaiQiCfg);
		rP(C.DingZhiHuaZhuangBei, P.DingZhiHuaZhuangBeiCfg);
		rP(C.QiRiDengLu, P.QiRiDengLuCfg);
		rP(C.DiaoLuoBao, P.DiaoLuoBaoCfg, "shibieid");
		rP(C.QianDao, P.QianDaoCfg);
		rP(C.TuZhiHeCheng, P.TuZhiHeChengCfg);
		rP(C.CangBaoGe, P.CangBaoGeCfg);
		rP(C.GongMingTuPu, P.GongMingTuPuCfg);
		rP(C.ChiBangHuanHua, P.ChiBangHuanHuaCfg);
		rP(C.ChuanQiZhiZun, P.ChuanQiZhiZunCfg);
		rP(C.ShaBaKeTiaoZhan, P.ShaBaKeTiaoZhanCfg);
		rP(C.ShaBaKePaiMing, P.ShaBaKePaiMingCfg);
		rP(C.GuanXingTai, P.GuanXingTaiCfg);
		rP(C.GuanXingTaiXingZuo, P.GuanXingTaiXingZuoCfg);
		rP(C.XianShiBoss, P.XianShiBossCfg, "ID");
		rP(C.ChengZhu, P.ChengZhuCfg);

		rE(C.JueSeWaiXian);
		rE(C.daoju);*/
	}
}